apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: topolvm-hook
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/mutatingwebhook
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
    app.kubernetes.io/name: topolvm-hook
webhooks:
  - name: pod-hook.topolvm.cybozu.com
    namespaceSelector:
      matchExpressions:
      - key: topolvm.cybozu.com/webhook
        operator: NotIn
        values: ["ignore"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: controller
        path: /pod/mutate
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
  - name: pvc-hook.topolvm.cybozu.com
    namespaceSelector:
      matchExpressions:
      - key: topolvm.cybozu.com/webhook
        operator: NotIn
        values: ["ignore"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: controller
        path: /pvc/mutate
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["persistentvolumeclaims"]
