# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: webhook-selfsign
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
spec:
  selfSigned: {}

---

# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: webhook-ca
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
spec:
  ca:
    secretName: webhook-ca