{{ if eq (lower .Values.scheduler.type) "deployment" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "topolvm.fullname" . }}-scheduler
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ template "topolvm.fullname" . }}-scheduler
  ports:
    - protocol: TCP
      port: {{ .Values.scheduler.options.listen.port }}
{{ end }}