kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topolvm-scheduler:psp:topolvm-scheduler
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:topolvm-scheduler
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: topolvm-scheduler
