kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:{{ template "topolvm.fullname" . }}-scheduler
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["topolvm-scheduler"]