kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "topolvm.fullname" . }}-scheduler:psp:{{ template "topolvm.fullname" . }}-scheduler
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:{{ template "topolvm.fullname" . }}-scheduler
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ template "topolvm.fullname" . }}-scheduler
